### ISSUE TITLE
Support Digital Ocean API v2

### ISSUE THREAD

**Issue by ariejan** [kapilt/juju-digitalocean#25]

**Comment by binary132** [comment]
Any chance this will receive some attention soon?

**Comment by chuckbutler** [comment]
This is becoming more important as the v2 api just left beta, and they have plans on depreciating the v1 api.

@kapilt  do you have plans on updating this or should one of us try to hack this in with their newly released oauth python module?

**Comment by kapilt** [comment]
I can have a look a it. One of the issues has been wanting to keep the dep
chain minimal. Vs using an extant library

**Comment by dangyogi** [comment]
The v1 DO api is no longer supported when the new DO teams are used for a project (such as mine).  Should I take a look at what it would take to move this project to v2, or use some kind of juju manual mode exclusively for DO, or ?? (new to juju and DO).

**Comment by chuckbutler** [comment]
Greetings @dangyogi 

I've spoken to @kapilt and we're both tight on the time budget for now. a V2 api contribution would be welcome. We're happy to review any code submissions that would satisfy the migration to v2 coming from the consumers of the library.

For now, as you cannot use the current Juju DO plugin since you don't have access to v1 api credentials you can get started with the manual provider. This does mean all of your provisioning is manual, and I apologize for not having a better response at this time.

With regard to moving ot V2, there are a few API libraries out there that you could consume to make the move. I know initially there was a blocker put in place wanting to limit the dependencies of the project, but I feel that with the community around this project growing, and our current time constraints, it should be a fairly trivial matter to integrate with the python-digitalocean library - which only adds an additional 2 dependencies, and update the provider to be v2 compliant.

If you have any submissions against this feel free to open a PR, and link to this bug and one of us will get you a review ASAP.

**Comment by andrewsomething** [comment]
Hey! I can probably find some time to work on this. Porting the API requests to use v2 either directly or using python-digitalocean should be fairly straight forward.

I know that there was an idea of using the metadata service/cloud-init that is available through v2 instead of using SSH, but I'm not well versed in the Juju internals. If that's still something that's wanted, I'd appreciate any pointers to other plugins doing something similar. Probably best to separate these two things...

**Comment by dangyogi** [comment]
FYI, I've already submitted a pull request with the v2 support.  I wasn't
able to test it on the v1 api though.  So if you could do that, it would be
helpful.  I also didn't update the tests.

**Comment by kapilt** [comment]
This just landed, testing appreciated

**Comment by kapilt** [comment]
Closed with #34
